ead:
  service-registry:
    username: serviceregistry
    password: 'ead123sr'
  auth:
    jwtSecret: KtMyJNrMuVqahZMIQRKTaSagmZz4MjwXy+3D0awL1XCe0MMhXawXgTIteLVqfXVyjCDJk4HgJf0189g8Steq509KPrBn2FlGc+6plqti0d4=
    jwtExpiration: 14400000

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.service-registry.username}:${ead.service-registry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost