server:
  port: 8084
  servlet:
    context-path: '/ead-notification'
  
spring:
  application:
    name: ead-notification-service
  datasource:
      url: jdbc:postgresql://localhost:5434/ead_notification
      username: postgres
      password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
  rabbitmq:
    addresses: amqps://rdhphlht:rgmyla9SjLQYRTRAoK8ImLsLnAuAiGnu@beaver.rmq.cloudamqp.com/rdhphlht
  output:
    ansi:
      enabled: always

ead:
  broker:
    exchange:
      notification-command-exchange: ead.notificationcommand
    queue: 
      notification-command-queue:
        name: ead.notificationcommand.ms.notification
    key:
      notification-command-key: ms.notification

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health